
# Build container

FROM node:lts-alpine as build

WORKDIR /build

ADD . .
RUN npm install


# Runtime container

FROM node:lts-alpine

RUN apk update && \
  apk add --no-cache curl

WORKDIR /app

COPY --from=build /build/node_modules node_modules/
COPY --from=build /build/client.sh .
COPY --from=build /build/client.js .
CMD ./client.sh